elasticsearch:
    image: elasticsearch:2.3
    ports:
        - "9200:9200"

kibana:
    image: kibana:4.5
    ports:
        - "5601:5601"
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
        - elasticsearch
